# Generated by Django 4.2.4 on 2023-09-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designation',
            new_name='reds',
        ),
    ]
