# Generated by Django 4.2.5 on 2023-09-29 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
    ]
