# Generated by Django 4.2.5 on 2023-09-29 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProfile',
        ),
    ]
